
server:
  port: 8762 #端口号

spring:
  application:
    name: cloud-test-user

  datasource:
    url: jdbc:mysql://192.168.0.244:3306/test?useSSL=false&useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=CONVERT_TO_NULL&jdbcCompliantTruncation=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: AaQwer_123
    initialSize: 5
    minIdle: 5
    maxActive: 50
    maxWait: 60000

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




