
server:
  port: 8763 #端口号

spring:
  application:
    name: cloud-test-service

  datasource:
    url: jdbc:mysql://192.168.0.244:3306/world?useSSL=false&useUnicode=true&characterEncoding=gbk&zeroDateTimeBehavior=CONVERT_TO_NULL&jdbcCompliantTruncation=false&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: AaQwer_123
    initialSize: 5
    minIdle: 5
    maxActive: 50
    maxWait: 60000

# Mybatis Mate 配置
mybatis-mate:
  cert:
    grant: thisIsTestLicense
    license: as/bsBaSVrsA9FfjC/N77ruEt2/QZDrW+MHETNuEuZBra5mlaXZU+DE1ZvF8UjzlLCpH3TFVH3WPV+Ya7Ugiz1Rx4wSh/FK6Ug9lhos7rnsNaRB/+mR30aXqtlLt4dAmLAOCT56r9mikW+t1DDJY8TVhERWMjEipbqGO9oe1fqYCegCEX8tVCpToKr5J1g1V86mNsNnEGXujnLlEw9jBTrGxAyQroD7Ns1Dhwz1K4Y188mvmRQp9t7OYrpgsC7N9CXq1s1c2GtvfItHArkqHE4oDrhaPjpbMjFWLI5/XqZDtW3D+AVcH7pTcYZn6vzFfDZEmfDFV5fQlT3Rc+GENEg==

feign:
  #hystrix:
  circuitbreaker:
    # 开启熔断器
    enabled: true

ribbon:
  # 远程请求调用的超时时间 5 秒
  ConnectTimeout: 15000
  # 连接后的等待处理的超时时间 30 分钟
  ReadTimeout: 1800000
  # 最大重试次数，当注册中心中可以找到服务，但是服务连不上时将会重试
  MaxAutoRetries: 1
  # 切换实例的重试次数
  MaxAutoRetriesNextServer: 1

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            # 触发熔断的超时时间
            timeoutInMilliseconds: 15000

#openfeign 是依赖于 ribbon 的，所以超时配置配置 ribbon
#ribbon 配置下的项必须使用驼峰，使用中横线会失效，虽然这看起来怪怪的
#重生次数建议设置为 0，否则会出现幂等性的问题，当然查询的无所谓
#熔断触发的超时时间应该大于 （ConnectTimeout + ReadTimeout）* （总重试次数 + 1）
#总重试次数 = MaxAutoRetries * MaxAutoRetriesNextServer + 1

# Logger Config
logging:
  level:
    com.tangyinzi.cloudtestservice: debug

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/




