# ==== manager-backend 管理后台 =====
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-test-service
rules:
  - apiGroups: [""]
    resources: ["endpoints"]
    verbs: ["get", "watch", "list"]
spec:
  replicas: 1
  strategy:
    type: Recreate
  progressDeadlineSeconds: 5
  selector:
    matchLabels:
      app: cloud-test-service
  template:
    metadata:
      labels:
        app: cloud-test-service
    spec:
      containers:
        - name: main
          image: registry.cloud.weizhi.com:5000/wzw/cloud-test-service:${version}
          imagePullPolicy: IfNotPresent
          env:
            - name: SERVER_PORT
              value: "80"
          ports:
            - containerPort: 80
              name: http

# ==== manager-alarm =====
---
apiVersion: v1
kind: Service
metadata:
  name: cloud-test-service
spec:
  type: NodePort
  selector:
    app: cloud-test-service
  ports:
    - port: 80
      name: http
      targetPort: http
      nodePort: 30124


