apiVersion: k8s.nginx.org/v1alpha1
kind: NginxIngressController
metadata:
  name: my-nginx-ingress-controller
  namespace: default
spec:
  type: deployment
  image:
    repository: nginx/nginx-ingress
    tag: 2.2.0
    pullPolicy: IfNotPresent
  serviceType: NodePort
  nginxPlus: False